### ISSUE TITLE
Optimize: "Updated Reporting" breaks the Extension.

### ISSUE THREAD

**Issue by lukasvermeer** [lukasvermeer/srm#12]
We should fix that. Also take into account that clicking the button does _not_ change the url, so doesn't rerun the check. 👎

**Comment by heinrich333** [comment]
Fixed in 649b27d 👍

**Comment by heinrich333** [comment]
Selecting a different goal, like with VWO earlier, removes the highlighting. Will adept VWO solution here soon.

**Comment by heinrich333** [comment]
Fixed in 69775e7
