### ISSUE TITLE
Figure out how to serve the Jekyll site locally for testing

### ISSUE THREAD

**Issue by lukasvermeer** [lukasvermeer/srm#35]
I've never actually tried to build the site locally. It uses Github Pages and a remote theme, so not sure how to get that working locally. Should be possible. Doesn't seem urgent. Maybe we should create an issue?

_Originally posted by @lukasvermeer in https://github.com/lukasvermeer/srm/pull/34#issuecomment-597249457_

**Comment by pauldria** [comment]
Yeah, not urgent. Just wanted to make sure I wasn't missing anything. I got it set up for https://github.com/pauldria/counter-factual (points to counter-factual.com) and like the just-the-docs theme so will be using it for myraff.com. 

After that's done I can set it up here. Once set up it's super nice.

**Comment by pauldria** [comment]
PR opened for this - just needed to add one file essentially, but also added a md file going over the changes. I'm OK if we want to fold it into README.md.

https://github.com/lukasvermeer/srm/pull/36

**Comment by lukasvermeer** [comment]
Yeah folding it into README.md seems a better place for this dev-specific thing.
